# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='list',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
